FROM tomee:9-jre17-microprofile

RUN rm -rf /usr/local/tomee/webapps/*
COPY target/acmeair-flightservice-java-6.1.war /usr/local/tomee/webapps/ROOT.war
RUN sed -i "s/8080/9080/g" conf/server.xml

ENV JAEGER_ENABLEMENT=true
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=true
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1
