FROM tomee:9-jre11-microprofile

RUN rm -rf /usr/local/tomee/webapps/*
COPY target/acmeair-flightservice-java-5.0.war /usr/local/tomee/webapps/ROOT.war
ENV JAVA_OPTS="-Dhttp.keepalive=true -Dhttp.maxConnections=100 -Dgeronimo.opentracing.span.converter.zipkin.logger.active=false"
RUN sed -i "s/8080/9080/g" conf/server.xml

ENV JAEGER_ENABLEMENT=true
ENV JAEGER_AGENT_HOST=jaeger
ENV JAEGER_REPORTER_LOG_SPANS=true
ENV JAEGER_SAMPLER_TYPE=const
ENV JAEGER_SAMPLER_PARAM=1
